'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import React from "react";
import { ThemeProvider } from '@material-tailwind/react';


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Rock Paper Scissors',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
            {children}
      </body>
    </html>
  )
}
