# baseURL
@baseURL = http://localhost:3030/auth

###
# User Signup
POST http://localhost:3030/auth/register
Content-Type: application/json

{
  "username": "user2",
  "email": "example2@email.com",
  "password": "pass"
}

###
# User Index
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "email": "example2@email.com",
  "password": "pass2"
}

###
# User Logout
POST http://localhost:3030/auth/logout
Content-Type: application/json
Authorization: Bearer XXXX

###
# Verify Token
GET http://localhost:3030/auth/verify/xxx
Content-Type: application/json
