# baseURL
@baseURL = http://localhost:3030/auth

###
# User Signup
POST http://localhost:3030/auth/register
Content-Type: application/json

{
  "username": "user3",
  "email": "example3@email.com",
  "password": "pass"
}

###
# User Index
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "email": "example3@email.com",
  "password": "pass3"
}

###
# User Logout
POST http://localhost:3030/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJmZjVhYmI4Zi0zN2E3LTRlYzYtYjlmNS03NzE5OTM1MDViZDYiLCJlbWFpbCI6ImV4YW1wbGUzQGVtYWlsLmNvbSIsImlhdCI6MTcwNzU4OTkxNiwiZXhwIjozNDIwMzYwMjMyfQ.OMFJbzsnJoY2qlXECgeV0rHPBw5vdVJ7H5rQTPYYk8E

###
# Verify Token
GET http://localhost:3030/auth/verify/xxx
Content-Type: application/json
